print('@@@ Curly Brace Quantifier @@@')
print('[INFO] This can be seen at https://www.regular-expressions.info/repeat.html')
print('{min} will match exactly min times.')
print('{min, max} will match exactly between min and max.')
print('{min, } will match between min and many times.')
print('{0, max} will match between 0 or max times.')
print('Thus {0,1} is the same as ?')
print('Thus {0, } is the same as *')
print('Thus {1, } is the same as +')