print('@@@ Starts With @@@')
print('Does abc start with a? ' + str('abc'.startswith('a')))
print('Does abc start with ab? ' + str('abc'.startswith('ab')))
print('Does abc start with abc? ' + str('abc'.startswith('abc')))
print('Does abc start with abcd? ' + str('abc'.startswith('abcd')))
print('\n@@@ Ends With @@@')
print('Does abc end with a? ' + str('abc'.endswith('a')))
print('Does abc end with ab? ' + str('abc'.endswith('ab')))
print('Does abc end with abc? ' + str('abc'.endswith('abc')))
print('Does abc end with abcd? ' + str('abc'.endswith('abcd')))
